version: "2.3"

services:

  unprotected-server:
    image: approov/elixir-phoenix:1.13
    build: ./
    networks:
      - default
    command: bash -c "mix deps.get && mix phx.server"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/unprotected-server/hello:/home/developer/workspace

  approov-token-check:
    image: approov/elixir-phoenix:1.13
    build: ./
    env_file: .env
    networks:
      - default
    command: bash -c "mix deps.get && mix phx.server"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-check/hello:/home/developer/workspace

  approov-token-binding-check:
    image: approov/elixir-phoenix:1.13
    build: ./
    env_file: .env
    networks:
      - default
    command: bash -c "mix deps.get && mix phx.server"
    ports:
      - ${HOST_IP:-127.0.0.1}:${HTTP_PORT:-8002}:${HTTP_PORT:-8002}
    volumes:
      - ./src/approov-protected-server/token-binding-check/hello:/home/developer/workspace

